#!/bin/bash

filename="repos"
dirActual=$(pwd)

while read -r line
do

  parteUsuario=$(echo $line| cut -d '@' -f 1)  
  
  parteRepo01=$(echo $line| cut -d ';' -f 2)  
  comienzoRepositorio=(${parteRepo01///commit/ })
  
  parteRepo02=$(echo $line| cut -d ';' -f 3)  
  
  commit01=${parteRepo01##*/}
  commit02=${parteRepo02##*/}
  
  parteA="-01"
  parteB="-02"
  
  if [ -n "$commit01" ]; then
    git clone $comienzoRepositorio.git $parteUsuario$parteA  
    cd $parteUsuario$parteA
    git reset --hard $commit01    
    cd $dirActual  
    cp -rf *.java ./$parteUsuario$parteA     
  fi  
  

  if [ -n "$commit02" ]; then
    git clone $comienzoRepositorio.git $parteUsuario$parteB  
    cd $parteUsuario$parteB
    git reset --hard $commit02
    cd $dirActual  
    cp -rf *.java ./$parteUsuario$parteB
  fi      
  
  
done < $filename

