#!/bin/bash

filename="repos"
dirActual=$(pwd)

while read -r line
do
  #Para cada repositorio...
  parteUsuario=$(echo $line| cut -d '@' -f 1)  
  
  parteRepo01=$(echo $line| cut -d ';' -f 2)  
  comienzoRepositorio=(${parteRepo01///commit/ })
  
  parteRepo02=$(echo $line| cut -d ';' -f 3)  
  
  commit01=${parteRepo01##*/}
  commit02=${parteRepo02##*/}
  
  parteA="-01"
  parteB="-02"
  
  if [ -n "$commit01" ]; then
    git clone $comienzoRepositorio.git $parteUsuario$parteA  
    cd $parteUsuario$parteA
    git reset --hard $commit01 
    
    #Elimina los archivos de Bluej si los hubiera
    rm *.bluej
    rm *.ctxt
    rm *.class
    
    #Convierte la codificación del archivo a UTF-8 para evitar problemas con caracteres extraños
    for f in *.java
    do
        codificacion=$(uchardet $f)
        echo $codificacion $f
        iconv -f $codificacion -t UTF-8 $f > $f.back
        mv $f.back $f
    done

    cd $dirActual  
    cp *.java ./$parteUsuario$parteA     
  fi  
  

  if [ -n "$commit02" ]; then
    git clone $comienzoRepositorio.git $parteUsuario$parteB  
    cd $parteUsuario$parteB
    git reset --hard $commit02
    
    #Elimina los archivos de Bluej si los hubiera    
    rm *.bluej
    rm *.ctxt
    rm *.class
    
    #Convierte la codificación del archivo a UTF-8 para evitar problemas con caracteres extraños    
    for f in *.java
    do
        codificacion=$(uchardet $f)
        echo $codificacion $f
        iconv -f $codificacion -t UTF-8 $f > $f.back
        mv $f.back $f
    done    
    
    cd $dirActual  
    cp *.java ./$parteUsuario$parteB
  fi      
  
  
done < $filename
